# Generated by Django 4.2 on 2023-05-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', 'initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='working_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
