# Generated by Django 4.2 on 2023-05-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_visit_working_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='working_time',
        ),
    ]
