# Generated by Django 4.2.1 on 2023-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60)),
            ],
        ),
    ]
