# Generated by Django 4.2 on 2023-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_visit_leaving_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='leaving_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
